@startuml modules
' title Modules
' high-level module architecture

skinparam componentStyle rectangle
' skinparam linetype ortho
left to right direction

package Stateful {
    component FSM.State
    component Orders {
        component HallOrders
        component CabOrders
    }
}

package Stateless {
    component FSM.Transition
    component Communicator
    component Hardware
}

Hardware --> FSM.State : Sensor updates
Hardware --> Orders : Button presses
FSM.Transition --> FSM.State : State updates
FSM.Transition --> Orders : Floor arrival
Communicator --> Orders : External orders

@enduml
