@startuml modules
title Modules
' Module-level component architecture

skinparam componentStyle rectangle
skinparam linetype ortho
' left to right direction

package "Controller" as Controller {
    component "FSM.State" as State
    component "Hardware" as Hardware
    component "Decision" as Decision
    component "FSM.Action" as Action

    Hardware --> State : update state
    State --> Hardware : set outputs
    Action --> State
    Action --> Decision
}

package "Orders" as Orders {
    component "Communicator" as Communicator
    component "HallOrders" as HallOrders
    component "CabOrders" as CabOrders

    ' HallOrders <-[Hidden]- CabOrders
    Communicator --> HallOrders
    Communicator --> CabOrders
}

Action ..> Orders : get orders
Hardware --> Orders : floor/button events
HallOrders ..> Controller : simulate
@enduml
